# Generated by Django 5.1.1 on 2024-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/iconProfileDefault.jpg', upload_to='profile_pictures/'),
        ),
    ]
